AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for Tairona Service Implementation


Resources:
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'lambda:*'
                Resource: '*'
        
  TaironaBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: tairona-lambdas-bucket
  
  TaironaApi: 
    Type: "AWS::ApiGateway::RestApi"
    Properties: 
      Name: tairona-api
      Description: API used for Tairona requests
      FailOnWarnings : true
  
  TaironaApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: ApiDeployment
      RestApiId:
        Ref: TaironaApi
      StageName: LATEST

  ResizeImageToSquareLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: resize-image-to-square-lambda-function
      Runtime: nodejs22.x
      Role: !GetAtt RootRole.Arn
      Handler: index.handler
      Code:
        S3Bucket: !Ref TaironaBucket
        S3Key: usecases.zip
      Description: This function is encharged of converting a rectangle image to square.
      TracingConfig:
        Mode: Active

  ResizeImageToSquareLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName:
        Fn::GetAtt:
        - ResizeImageToSquareLambdaFunction
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: TaironaApi
          - "/*"

  ResizeImageToSquareResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId:
        Ref: TaironaApi
      ParentId:
        Fn::GetAtt:
        - TaironaApi
        - RootResourceId
      PathPart: resize-image-to-square

  ResizeImageToSquareRequest:
    DependsOn: ResizeImageToSquareLambdaPermission
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Join:
          - ''
          - - 'arn:aws:apigateway:'
            - Ref: AWS::Region
            - ":lambda:path/2015-03-31/functions/"
            - Fn::GetAtt:
              - ResizeImageToSquareLambdaFunction
              - Arn
            - "/invocations"
        IntegrationResponses:
        - StatusCode: 200

      ResourceId:
        Ref: ResizeImageToSquareResource
      RestApiId:
        Ref: TaironaApi
      MethodResponses:
      - StatusCode: 200

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ResizeImageToSquareRequest
    Properties:
      RestApiId:
        Ref: TaironaApi
      StageName: InitStage