name: WEB
'on':
  push:
    branches:
      - main
    paths:
      - server/**
  workflow_dispatch:

jobs:
  SERVER-CHANNEL-DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: DOWNLOAD REPOSITORY
        uses: actions/checkout@v2
      
      - name: USE NODE.JS 
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: INSTALL NODE DEPENDENCIES
        run: |
          cd server
          npm i

      - name: BUILD 
        run: |
          cd server
          npm run build
          cp -r node_modules dist/

      - name: Crear ZIP
        run: |
          cd server
          zip -r usecases.zip src/index.js package.json node_modules

      - name: AWS CONFIGURATION
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: S3 UPLOADING
        run: aws s3 cp server/usecases.zip s3://tairona-lambdas-bucket/usecases.zip